/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Sign a customer in with email or phone number and password
     * @description ADR-0014. identity-service normalises the address, finds its opaque
     *     Kratos handle through the keyed lookup hash and runs a Kratos native
     *     (API) login flow on the customer's behalf. The handle never leaves the
     *     server. Unknown addresses run the same flow with a random decoy
     *     handle, so the answer is identical: 400 `auth_flow_rejected` with
     *     `errors[{field: "form", code: "4000006"}]`.
     *
     *     Rejections carry Kratos message ids only (`field` is `login`,
     *     `password` or `form`); never the flow. The password is never logged
     *     or stored. Rate limited per client IP (IPv6 per /64) 20/min and
     *     200/day, per /24 (/48) network, and per account for failed attempts
     *     (10/15 min, 50/day) → 429 `rate_limited`.
     */
    post: operations["customerLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/registration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register a customer with email or phone number and password
     * @description ADR-0014. Stores the address encrypted under a new random handle (or
     *     re-uses the handle of an earlier, unfinished registration of the same
     *     address) and runs a Kratos native registration flow with
     *     `traits.login_id = <handle>`. Kratos sends the verification code; the
     *     app submits it to Kratos directly with `verification_flow_id`.
     *     Password policy and duplicate errors come back as 400
     *     `auth_flow_rejected` (e.g. `password`/`4000032`, `login`/`4000007`).
     *     Rate limited per client IP 5/min and 30/day, and per network.
     */
    post: operations["customerRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/recovery": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start password recovery by code for an email or phone number
     * @description ADR-0014. Starts a Kratos native recovery flow (method `code`) for the
     *     address's handle — or a random decoy handle when there is no account,
     *     so the response has the same shape every time. A code is delivered
     *     (email or SMS) only when the account exists.
     *
     *     The response carries `recovery_id`, the flow id sealed by
     *     identity-service: never the Kratos flow id, because anyone can read a
     *     Kratos recovery flow by id and it shows the handle. The app submits
     *     the code with `POST /v1/auth/recovery/code`, then sets the new
     *     password in the returned settings flow at Kratos directly. Same rate
     *     limits as login (per IP and network).
     */
    post: operations["customerRecovery"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/auth/recovery/code": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a recovery code
     * @description ADR-0014. Submits the 6-digit code on the recovery flow behind
     *     `recovery_id`. A valid code returns Kratos's privileged session token
     *     and the settings flow to set the new password in (directly at
     *     Kratos, `X-Session-Token`). A wrong code is 400 `auth_flow_rejected`
     *     (`form`/`4060006`); an expired flow 410 `auth_flow_expired` (start
     *     again with `POST /v1/auth/recovery`). Same rate limits as login.
     */
    post: operations["customerRecoveryCode"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current customer profile */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current customer's profile (requires verified email) */
    patch: operations["updateMe"];
    trace?: never;
  };
  "/v1/me/personal-info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the caller's decrypted personal information
     * @description Values are decrypted in memory for this response only. Fields never set
     *     are `null`. 503 `dependency_unavailable` when the key manager is down.
     */
    get: operations["getMyPersonalInfo"];
    /**
     * Replace the caller's personal information (verified email required)
     * @description Full replacement: omitted or `null` fields are cleared. Validation errors
     *     name the field and code only; submitted values are never echoed.
     */
    put: operations["putMyPersonalInfo"];
    post?: never;
    /**
     * Erase the caller's personal information (crypto-shredding; any authenticated customer)
     * @description Destroys the caller's data key and deletes the encrypted record. Idempotent.
     */
    delete: operations["eraseMyPersonalInfo"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current admin session; the only admin endpoint reachable at AAL1
     * @description 403 codes drive the admin web routing: `not_admin`, `aal2_required`,
     *     `mfa_enrollment_required`.
     */
    get: operations["getAdminMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List customers (permission view_customers) */
    get: operations["listCustomers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/lookup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Find customers by personal-info phone number or by login identifier (permission view_customers)
     * @description Exactly one of `phone_number` (self-declared personal-info phone, blind
     *     index) or `login` (email or phone the customer signs in with; exact
     *     match) must be set. Values travel in the body so they never appear in
     *     URLs or access logs. A `login` lookup is charged one unit and audited as
     *     `customer.login.lookup` (kind and matched ids only).
     *     Rate limited per actor (30/min, 200/day → 429 `rate_limited`), charged per candidate
     *     examined (minimum 1 per call); every call is audited. Phone numbers are self-declared
     *     (phone_verified: false): several customers may claim the same number, at most 20
     *     candidates are examined and `truncated` reports more.
     */
    post: operations["lookupCustomers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/personal-info": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    /** Masked personal information (permission view_customers) */
    get: operations["getCustomerPersonalInfoMasked"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/personal-info/reveal": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reveal full personal information with a reason (permission reveal_customer_pii; audited)
     * @description Order: decrypt in memory → commit audit event `customer.pii.revealed`
     *     (actor, target, fields, reason_code, ticket_ref) → respond. If the audit
     *     row cannot be written, buffers are zeroed and nothing is revealed (500).
     *     Rate limited per actor (20/hour → 429 `rate_limited`).
     */
    post: operations["revealCustomerPersonalInfo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    /** Get one customer (permission view_customers) */
    get: operations["getCustomer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable a customer and revoke all sessions (permission manage_customers; idempotent) */
    post: operations["disableCustomer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/enable": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-enable a customer (permission manage_customers; idempotent) */
    post: operations["enableCustomer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke all sessions of a customer (permission manage_customers) */
    delete: operations["revokeCustomerSessions"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/admins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List admins (permission manage_admins) */
    get: operations["listAdmins"];
    put?: never;
    /** Invite an admin (permission manage_admins). The invitation link is emailed, never returned. */
    post: operations["inviteAdmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/admins/{id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    /** Change an admin's role (permission manage_admins; not self; keeps >= 1 super_admin) */
    put: operations["changeAdminRole"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit events, newest first (permission view_audit) */
    get: operations["listAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/m2m/v1/customers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    /** Customer status for service clients (scope customers:read); no personal data */
    get: operations["getMachineCustomer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/m2m/v1/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List audit events, newest first (scope audit:read)
     * @description Filtered view: only allowlisted actions (customer state changes, admin.*,
     *     service_client.*) and allowlisted detail keys. Personal-data actions
     *     (`customer.pii.*`) are never exposed to machines.
     */
    get: operations["listMachineAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/service-clients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List machine clients managed by identity-service (permission manage_service_clients) */
    get: operations["listServiceClients"];
    put?: never;
    /**
     * Register a client_credentials client (permission manage_service_clients; secret returned once)
     * @description The secret is in this response only and is never stored by identity-service.
     *     A replay with the same Idempotency-Key returns the client without `client_secret`;
     *     use rotate-secret if it was lost.
     */
    post: operations["createServiceClient"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/service-clients/{client_id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: components["parameters"]["ClientId"];
      };
      cookie?: never;
    };
    /** Get one machine client (permission manage_service_clients) */
    get: operations["getServiceClient"];
    put?: never;
    post?: never;
    /** Delete a machine client; its tokens stop working within 30 s (permission manage_service_clients) */
    delete: operations["deleteServiceClient"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/service-clients/{client_id}/rotate-secret": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: components["parameters"]["ClientId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Replace the client secret; the old one stops working immediately (permission manage_service_clients) */
    post: operations["rotateServiceClientSecret"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/after-registration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Kratos after-registration webhook (profile provisioning) */
    post: operations["kratosAfterRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/pre-registration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Kratos pre-persist registration check (response.parse true)
     * @description ADR-0013 / PLI-FR-04. Rejects a registration whose `login_id` is not a
     *     handle stored by identity-service (ADR-0014), a legacy `email` trait, or
     *     (during the migration) an address a legacy customer already uses. 200
     *     allows; 400 carries Kratos-formatted messages on `#/traits/login_id`
     *     (ids 4049001 legacy traits, 4049002 unresolved, 4000007 duplicate).
     */
    post: operations["kratosPreRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/courier": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Kratos courier http delivery (verification / recovery codes)
     * @description ADR-0013 / PLI-FR-05. Kratos `courier.delivery_strategy: http`. The
     *     recipient is a pseudonym (customers) or an admin's email; the service
     *     resolves it and sends its own localised message by email or SMS.
     *     Authenticated with the courier key (not the webhook key). 204 = sent,
     *     duplicate or permanently dropped (no retry); 503 = transient (Kratos
     *     retries).
     */
    post: operations["kratosCourier"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/after-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Kratos after-login population guard
     * @description Interrupting population guard (ADR-0004). Returns 204 to allow, or 403
     *     with a Kratos-formatted message body to interrupt the login.
     */
    post: operations["kratosAfterLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Problem: {
      /** @example https://docs.go-ory-auth-example.local/problems/aal2-required */
      type: string;
      title: string;
      status: number;
      /**
       * @description Stable machine code. Known values: unauthenticated, forbidden, not_admin,
       *     aal2_required, mfa_enrollment_required, email_not_verified, not_found,
       *     conflict, validation_failed, rate_limited, dependency_unavailable, internal,
       *     invalid_request, invalid_token, insufficient_scope (machine plane; also sent in `WWW-Authenticate`),
       *     auth_flow_rejected (400, /v1/auth/*: Kratos rejected the flow; `errors[].code` is the Kratos message id,
       *     `errors[].field` is login, password or form), auth_flow_expired (410, /v1/auth/recovery/code: start again).
       *     Clients must tolerate unknown values.
       */
      code: string;
      detail?: string;
      request_id?: string;
      errors?: components["schemas"]["FieldError"][];
    };
    FieldError: {
      field: string;
      /** @example too_long */
      code: string;
    };
    PersonName: {
      first?: string;
      last?: string;
    };
    /** @enum {string} */
    IdentityState: "active" | "inactive";
    /** @enum {string} */
    Role: "support" | "admin" | "super_admin";
    /** @enum {string} */
    Permission:
      | "view_customers"
      | "manage_customers"
      | "manage_admins"
      | "view_audit"
      | "reveal_customer_pii"
      | "manage_service_clients";
    Me: {
      /** Format: uuid */
      id: string;
      login: components["schemas"]["LoginIdentifier"];
      /**
       * Format: email
       * @deprecated
       * @description Present only when login.type is email. Use `login`.
       */
      email?: string;
      /** @description The login identifier (email or phone) is verified; the name is kept for compatibility */
      email_verified: boolean;
      /**
       * @deprecated
       * @description Never returned. The customer's name is encrypted personal info (GET /v1/me/personal-info).
       */
      name?: components["schemas"]["PersonName"];
      /** @description Optional nickname; not the real name */
      display_name?: string | null;
      avatar_url?: string | null;
      /** @example vi-VN */
      locale: string;
      /** Format: date-time */
      created_at: string;
    };
    UpdateMeRequest: {
      display_name?: string | null;
      avatar_url?: string | null;
      locale?: string;
    };
    Address: {
      line1: string;
      line2?: string | null;
      city: string;
      region?: string | null;
      postal_code?: string | null;
      /** @description ISO 3166-1 alpha-2 */
      country: string;
    };
    NationalId: {
      /** @enum {string} */
      type: "cccd" | "passport" | "other";
      /** @description Upper-cased, ^[A-Z0-9]{6,20}$ */
      number: string;
    };
    /** @description Customer PII. Stored encrypted (AES-256-GCM, per-customer key). */
    PersonalInfo: {
      /** @description Real name. Each part trimmed, no control characters; both parts empty = absent */
      name?: components["schemas"]["PersonName"] | null;
      /**
       * @description E.164; spaces, dashes and dots are stripped
       * @example +84901234567
       */
      phone_number?: string | null;
      /** Format: date */
      date_of_birth?: string | null;
      address?: components["schemas"]["Address"] | null;
      national_id?: components["schemas"]["NationalId"] | null;
      /** Format: date-time */
      readonly updated_at?: string | null;
    };
    /** @description Reveal response. Personal info fields (as PersonalInfo) plus the login identifier. */
    RevealedPersonalInfo: {
      name?: components["schemas"]["PersonName"] | null;
      phone_number?: string | null;
      /** Format: date */
      date_of_birth?: string | null;
      address?: components["schemas"]["Address"] | null;
      national_id?: components["schemas"]["NationalId"] | null;
      /** Format: date-time */
      updated_at?: string | null;
      login?: components["schemas"]["LoginIdentifier"] | null;
    };
    /** @enum {string} */
    LoginType: "email" | "phone";
    LoginIdentifier: {
      type: components["schemas"]["LoginType"];
      /** @description Email (lower-cased) or phone (E.164) in responses; as typed in requests */
      value: string;
    };
    MaskedLogin: {
      type: components["schemas"]["LoginType"];
      /**
       * @description Email: first character of local part and domain label + TLD; phone: calling code + 7 stars + last 3
       * @example a***@e***.com
       */
      masked: string;
    };
    CustomerCredentials: {
      login: components["schemas"]["LoginIdentifier"];
      /** Format: password */
      password: string;
    };
    CustomerRecoveryRequest: {
      login: components["schemas"]["LoginIdentifier"];
    };
    CustomerAuthSession: {
      /** @description Kratos session token (store in secure storage; send as Bearer to /v1 and X-Session-Token to Kratos) */
      session_token: string;
      /** @description The Kratos session object, as returned by Kratos to its owner */
      session: {
        [key: string]: unknown;
      };
      /**
       * Format: uuid
       * @description Registration only, when Kratos started a verification flow (code already sent)
       */
      verification_flow_id?: string;
    };
    CustomerRecoveryStarted: {
      /** @description Opaque reference to the recovery flow (sealed by identity-service); send it back with the code */
      recovery_id: string;
    };
    CustomerRecoveryCodeRequest: {
      recovery_id: string;
      code: string;
    };
    CustomerRecoveryGrant: {
      /** @description Privileged Kratos session token (store it only after the new password is set) */
      session_token: string;
      /** @description Kratos native settings flow for the new password */
      settings_flow_id: string;
    };
    MaskedPersonalInfo: {
      /** @description First character of each part + fixed "***" */
      name?: {
        /** @example A*** */
        first?: string | null;
        /** @example N*** */
        last?: string | null;
      } | null;
      /**
       * @description Calling code + fixed 7 stars + last 3
       * @example +84*******567
       */
      phone_number?: string | null;
      /** @example 1990-**-** */
      date_of_birth?: string | null;
      address?: {
        city?: string;
        country?: string;
      } | null;
      national_id?: {
        /** @enum {string} */
        type?: "cccd" | "passport" | "other";
        /**
         * @description Fixed 6 stars; last 3 only when the number has ≥ 9 characters
         * @example ******123
         */
        number?: string;
      } | null;
      has_name: boolean;
      has_phone_number: boolean;
      has_date_of_birth: boolean;
      has_address: boolean;
      has_national_id: boolean;
      /** Format: date-time */
      updated_at?: string | null;
    };
    /** @description Free-text reasons are not accepted because the audit log is append-only and must never hold PII. */
    RevealRequest: {
      /** @enum {string} */
      reason_code:
        | "customer_support_request"
        | "identity_verification"
        | "fraud_investigation"
        | "legal_request";
      /** @example SUP-1234 */
      ticket_ref?: string;
      /** @description Fields to reveal (data minimisation). Omitted = all. */
      fields?: ("name" | "phone_number" | "date_of_birth" | "address" | "national_id" | "login")[];
    };
    /** @description Exactly one of phone_number or login (else 422 validation_failed, field body, code one_of). */
    CustomerLookupRequest: {
      /** @example +84901234567 */
      phone_number?: string;
      login?: components["schemas"]["LoginIdentifier"];
    };
    /** @description Matches by self-declared phone number (phone_verified false); not proof of ownership. */
    CustomerLookupResult: {
      /** @description More than 20 records carry this phone number; only the first 20 were examined. */
      truncated: boolean;
      items: {
        /** Format: uuid */
        id: string;
        state?: components["schemas"]["IdentityState"];
        personal_info: components["schemas"]["MaskedPersonalInfo"];
        login?: components["schemas"]["MaskedLogin"];
      }[];
    };
    /** @enum {string} */
    MachineScope: "customers:read" | "audit:read";
    MachineCustomer: {
      /** Format: uuid */
      id: string;
      state: components["schemas"]["IdentityState"];
      email_verified: boolean;
      /** Format: date-time */
      created_at: string;
    };
    MachineAuditEvent: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      occurred_at: string;
      /** Format: uuid */
      actor_id: string;
      action: string;
      target_type: string;
      target_id: string;
      /** @description Allowlisted keys only (role, previous_role, scopes, name). */
      details?: {
        role?: string;
        previous_role?: string;
        scopes?: string[];
        name?: string;
      };
    };
    MachineAuditEventPage: {
      items: components["schemas"]["MachineAuditEvent"][];
      next_page_token?: string | null;
    };
    CreateServiceClientRequest: {
      /** @example billing-sync */
      name: string;
      /**
       * Format: email
       * @description Contact responsible for the client
       */
      owner: string;
      scopes: components["schemas"]["MachineScope"][];
    };
    ServiceClient: {
      client_id: string;
      name: string;
      /** Format: email */
      owner: string;
      scopes: components["schemas"]["MachineScope"][];
      /** Format: date-time */
      created_at: string;
      /** Format: uuid */
      created_by?: string | null;
    };
    ServiceClientWithSecret: components["schemas"]["ServiceClient"] & {
      /** @description Present only on create and rotate. Never stored by identity-service. */
      client_secret?: string;
    };
    ServiceClientList: {
      items: components["schemas"]["ServiceClient"][];
    };
    AdminMe: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      /** @enum {string} */
      aal: "aal1" | "aal2";
      roles: components["schemas"]["Role"][];
      permissions: components["schemas"]["Permission"][];
      /** Format: date-time */
      session_expires_at: string;
    };
    Customer: {
      /** Format: uuid */
      id: string;
      /**
       * Format: email
       * @deprecated
       * @description Never returned for customers (ADR-0013). Use `login`.
       */
      email?: string;
      /** @description Masked login identifier; null when it could not be read */
      login?: components["schemas"]["MaskedLogin"] | null;
      /** @description The key manager was unavailable; `login` is null for pseudonymous customers */
      login_unavailable: boolean;
      /** @description The login identifier is verified */
      email_verified: boolean;
      /**
       * @deprecated
       * @description Never returned for customers. The name is encrypted personal info (masked via /admin/v1/customers/{id}/personal-info).
       */
      name?: components["schemas"]["PersonName"];
      state: components["schemas"]["IdentityState"];
      /** @description Optional nickname; not the real name */
      display_name?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    CustomerPage: {
      items: components["schemas"]["Customer"][];
      next_page_token?: string;
    };
    CustomerState: {
      /** Format: uuid */
      id: string;
      state: components["schemas"]["IdentityState"];
    };
    ReasonRequest: {
      reason?: string;
    };
    Admin: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      role: components["schemas"]["Role"];
      state: components["schemas"]["IdentityState"];
      mfa_enrolled?: boolean;
      /** Format: date-time */
      created_at: string;
    };
    AdminPage: {
      items: components["schemas"]["Admin"][];
      next_page_token?: string;
    };
    InviteAdminRequest: {
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      role: components["schemas"]["Role"];
    };
    InvitedAdmin: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      role: components["schemas"]["Role"];
      /** Format: date-time */
      invitation_expires_at: string;
    };
    ChangeRoleRequest: {
      role: components["schemas"]["Role"];
    };
    AuditEvent: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      occurred_at: string;
      /** Format: uuid */
      actor_id: string;
      /** @example customer.disabled */
      action: string;
      /** @example customer */
      target_type: string;
      target_id: string;
      request_id: string;
      details: {
        [key: string]: unknown;
      };
    };
    AuditEventPage: {
      items: components["schemas"]["AuditEvent"][];
      next_page_token?: string;
    };
    KratosHookPayload: {
      /** Format: uuid */
      identity_id: string;
      schema_id: string;
      /** @enum {string} */
      flow_type: "api" | "browser";
      /** @description after-registration only: the customer's pseudonymous login_id (binds the vault entry) */
      login_id?: string;
    };
    KratosPreRegistrationPayload: {
      schema_id: string;
      flow_type?: string;
      login_id?: string | null;
      /** @description legacy trait; always rejected */
      email?: string | null;
    };
    KratosCourierPayload: {
      recipient: string;
      template_type: string;
      /** Format: uuid */
      identity_id?: string | null;
      code?: string | null;
      expires_in_minutes?: number | null;
    };
  };
  responses: {
    /** @description Error (RFC 9457) */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    ClientId: string;
    IdentityId: string;
    PageSize: number;
    PageToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  customerLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerCredentials"];
      };
    };
    responses: {
      /** @description Signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerAuthSession"];
        };
      };
      400: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  customerRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerCredentials"];
      };
    };
    responses: {
      /** @description Registered and signed in */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerAuthSession"];
        };
      };
      400: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  customerRecovery: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerRecoveryRequest"];
      };
    };
    responses: {
      /** @description Recovery flow started */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerRecoveryStarted"];
        };
      };
      400: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  customerRecoveryCode: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerRecoveryCodeRequest"];
      };
    };
    responses: {
      /** @description Code accepted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerRecoveryGrant"];
        };
      };
      400: components["responses"]["Problem"];
      410: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  getMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  putMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonalInfo"];
      };
    };
    responses: {
      /** @description Stored */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  eraseMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Erased */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  getAdminMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminMe"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  listCustomers: {
    parameters: {
      query?: {
        state?: components["schemas"]["IdentityState"];
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  lookupCustomers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerLookupRequest"];
      };
    };
    responses: {
      /** @description Matches (possibly empty) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerLookupResult"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getCustomerPersonalInfoMasked: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaskedPersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  revealCustomerPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevealRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RevealedPersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  disableCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReasonRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerState"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  enableCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReasonRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerState"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  revokeCustomerSessions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  listAdmins: {
    parameters: {
      query?: {
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  inviteAdmin: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteAdminRequest"];
      };
    };
    responses: {
      /** @description Invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitedAdmin"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  changeAdminRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeRoleRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Admin"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        target_type?: string;
        target_id?: string;
        actor_id?: string;
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  getMachineCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MachineCustomer"];
        };
      };
      400: components["responses"]["Problem"];
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  listMachineAuditEvents: {
    parameters: {
      query?: {
        target_type?: string;
        target_id?: string;
        actor_id?: string;
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MachineAuditEventPage"];
        };
      };
      400: components["responses"]["Problem"];
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  listServiceClients: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceClientList"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  createServiceClient: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateServiceClientRequest"];
      };
    };
    responses: {
      /** @description Created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceClientWithSecret"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getServiceClient: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: components["parameters"]["ClientId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceClient"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  deleteServiceClient: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: components["parameters"]["ClientId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Deleted */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  rotateServiceClientSecret: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        client_id: components["parameters"]["ClientId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description New secret (shown once) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ServiceClientWithSecret"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  kratosAfterRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosHookPayload"];
      };
    };
    responses: {
      /** @description Processed (idempotent) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  kratosPreRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosPreRegistrationPayload"];
      };
    };
    responses: {
      /** @description Allowed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Rejected (Kratos webhook message format) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Dependency unavailable (registration fails */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  kratosCourier: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosCourierPayload"];
      };
    };
    responses: {
      /** @description Handled */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Transient failure */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  kratosAfterLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosHookPayload"];
      };
    };
    responses: {
      /** @description Allowed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Login interrupted (Kratos webhook message format) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
