/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Current customer profile */
    get: operations["getMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update the current customer's profile (requires verified email) */
    patch: operations["updateMe"];
    trace?: never;
  };
  "/v1/me/personal-info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Read the caller's decrypted personal information
     * @description Values are decrypted in memory for this response only. Fields never set
     *     are `null`. 503 `dependency_unavailable` when the key manager is down.
     */
    get: operations["getMyPersonalInfo"];
    /**
     * Replace the caller's personal information (verified email required)
     * @description Full replacement: omitted or `null` fields are cleared. Validation errors
     *     name the field and code only; submitted values are never echoed.
     */
    put: operations["putMyPersonalInfo"];
    post?: never;
    /**
     * Erase the caller's personal information (crypto-shredding; any authenticated customer)
     * @description Destroys the caller's data key and deletes the encrypted record. Idempotent.
     */
    delete: operations["eraseMyPersonalInfo"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Current admin session; the only admin endpoint reachable at AAL1
     * @description 403 codes drive the admin web routing: `not_admin`, `aal2_required`,
     *     `mfa_enrollment_required`.
     */
    get: operations["getAdminMe"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List customers (permission view_customers) */
    get: operations["listCustomers"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/lookup": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Find customers by phone number via the blind index (permission view_customers)
     * @description The phone number travels in the body so it never appears in URLs or access logs.
     *     Rate limited per actor (30/min, 200/day → 429 `rate_limited`), charged per candidate
     *     examined (minimum 1 per call); every call is audited. Phone numbers are self-declared
     *     (phone_verified: false): several customers may claim the same number, at most 20
     *     candidates are examined and `truncated` reports more.
     */
    post: operations["lookupCustomers"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/personal-info": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    /** Masked personal information (permission view_customers) */
    get: operations["getCustomerPersonalInfoMasked"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/personal-info/reveal": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reveal full personal information with a reason (permission reveal_customer_pii; audited)
     * @description Order: decrypt in memory → commit audit event `customer.pii.revealed`
     *     (actor, target, fields, reason_code, ticket_ref) → respond. If the audit
     *     row cannot be written, buffers are zeroed and nothing is revealed (500).
     *     Rate limited per actor (20/hour → 429 `rate_limited`).
     */
    post: operations["revealCustomerPersonalInfo"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    /** Get one customer (permission view_customers) */
    get: operations["getCustomer"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/disable": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Disable a customer and revoke all sessions (permission manage_customers; idempotent) */
    post: operations["disableCustomer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/enable": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Re-enable a customer (permission manage_customers; idempotent) */
    post: operations["enableCustomer"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/customers/{id}/sessions": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke all sessions of a customer (permission manage_customers) */
    delete: operations["revokeCustomerSessions"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/admins": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List admins (permission manage_admins) */
    get: operations["listAdmins"];
    put?: never;
    /** Invite an admin (permission manage_admins). The invitation link is emailed, never returned. */
    post: operations["inviteAdmin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/admins/{id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    get?: never;
    /** Change an admin's role (permission manage_admins; not self; keeps >= 1 super_admin) */
    put: operations["changeAdminRole"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/admin/v1/audit-events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List audit events, newest first (permission view_audit) */
    get: operations["listAuditEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/after-registration": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Kratos after-registration webhook (profile provisioning) */
    post: operations["kratosAfterRegistration"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/hooks/kratos/after-login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Kratos after-login population guard
     * @description Interrupting population guard (ADR-0004). Returns 204 to allow, or 403
     *     with a Kratos-formatted message body to interrupt the login.
     */
    post: operations["kratosAfterLogin"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Problem: {
      /** @example https://docs.go-ory-auth-example.local/problems/aal2-required */
      type: string;
      title: string;
      status: number;
      /**
       * @description Stable machine code. Known values: unauthenticated, forbidden, not_admin,
       *     aal2_required, mfa_enrollment_required, email_not_verified, not_found,
       *     conflict, validation_failed, rate_limited, dependency_unavailable, internal.
       *     Clients must tolerate unknown values.
       */
      code: string;
      detail?: string;
      request_id?: string;
      errors?: components["schemas"]["FieldError"][];
    };
    FieldError: {
      field: string;
      /** @example too_long */
      code: string;
    };
    PersonName: {
      first?: string;
      last?: string;
    };
    /** @enum {string} */
    IdentityState: "active" | "inactive";
    /** @enum {string} */
    Role: "support" | "admin" | "super_admin";
    /** @enum {string} */
    Permission:
      | "view_customers"
      | "manage_customers"
      | "manage_admins"
      | "view_audit"
      | "reveal_customer_pii";
    Me: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      email_verified: boolean;
      name?: components["schemas"]["PersonName"];
      display_name?: string | null;
      avatar_url?: string | null;
      /** @example vi-VN */
      locale: string;
      /** Format: date-time */
      created_at: string;
    };
    UpdateMeRequest: {
      display_name?: string | null;
      avatar_url?: string | null;
      locale?: string;
    };
    Address: {
      line1: string;
      line2?: string | null;
      city: string;
      region?: string | null;
      postal_code?: string | null;
      /** @description ISO 3166-1 alpha-2 */
      country: string;
    };
    NationalId: {
      /** @enum {string} */
      type: "cccd" | "passport" | "other";
      /** @description Upper-cased, ^[A-Z0-9]{6,20}$ */
      number: string;
    };
    /** @description Customer PII. Stored encrypted (AES-256-GCM, per-customer key). */
    PersonalInfo: {
      /**
       * @description E.164; spaces, dashes and dots are stripped
       * @example +84901234567
       */
      phone_number?: string | null;
      /** Format: date */
      date_of_birth?: string | null;
      address?: components["schemas"]["Address"] | null;
      national_id?: components["schemas"]["NationalId"] | null;
      /** Format: date-time */
      readonly updated_at?: string | null;
    };
    MaskedPersonalInfo: {
      /**
       * @description Calling code + fixed 7 stars + last 3
       * @example +84*******567
       */
      phone_number?: string | null;
      /** @example 1990-**-** */
      date_of_birth?: string | null;
      address?: {
        city?: string;
        country?: string;
      } | null;
      national_id?: {
        /** @enum {string} */
        type?: "cccd" | "passport" | "other";
        /**
         * @description Fixed 6 stars; last 3 only when the number has ≥ 9 characters
         * @example ******123
         */
        number?: string;
      } | null;
      has_phone_number: boolean;
      has_date_of_birth: boolean;
      has_address: boolean;
      has_national_id: boolean;
      /** Format: date-time */
      updated_at?: string | null;
    };
    /** @description Free-text reasons are not accepted because the audit log is append-only and must never hold PII. */
    RevealRequest: {
      /** @enum {string} */
      reason_code:
        | "customer_support_request"
        | "identity_verification"
        | "fraud_investigation"
        | "legal_request";
      /** @example SUP-1234 */
      ticket_ref?: string;
      /** @description Fields to reveal (data minimisation). Omitted = all. */
      fields?: ("phone_number" | "date_of_birth" | "address" | "national_id")[];
    };
    CustomerLookupRequest: {
      /** @example +84901234567 */
      phone_number: string;
    };
    /** @description Matches by self-declared phone number (phone_verified false); not proof of ownership. */
    CustomerLookupResult: {
      /** @description More than 20 records carry this phone number; only the first 20 were examined. */
      truncated: boolean;
      items: {
        /** Format: uuid */
        id: string;
        state?: components["schemas"]["IdentityState"];
        personal_info: components["schemas"]["MaskedPersonalInfo"];
      }[];
    };
    AdminMe: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      /** @enum {string} */
      aal: "aal1" | "aal2";
      roles: components["schemas"]["Role"][];
      permissions: components["schemas"]["Permission"][];
      /** Format: date-time */
      session_expires_at: string;
    };
    Customer: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      email_verified: boolean;
      name?: components["schemas"]["PersonName"];
      state: components["schemas"]["IdentityState"];
      display_name?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    CustomerPage: {
      items: components["schemas"]["Customer"][];
      next_page_token?: string;
    };
    CustomerState: {
      /** Format: uuid */
      id: string;
      state: components["schemas"]["IdentityState"];
    };
    ReasonRequest: {
      reason?: string;
    };
    Admin: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      role: components["schemas"]["Role"];
      state: components["schemas"]["IdentityState"];
      mfa_enrolled?: boolean;
      /** Format: date-time */
      created_at: string;
    };
    AdminPage: {
      items: components["schemas"]["Admin"][];
      next_page_token?: string;
    };
    InviteAdminRequest: {
      /** Format: email */
      email: string;
      name?: components["schemas"]["PersonName"];
      role: components["schemas"]["Role"];
    };
    InvitedAdmin: {
      /** Format: uuid */
      id: string;
      /** Format: email */
      email: string;
      role: components["schemas"]["Role"];
      /** Format: date-time */
      invitation_expires_at: string;
    };
    ChangeRoleRequest: {
      role: components["schemas"]["Role"];
    };
    AuditEvent: {
      /** Format: int64 */
      id: number;
      /** Format: date-time */
      occurred_at: string;
      /** Format: uuid */
      actor_id: string;
      /** @example customer.disabled */
      action: string;
      /** @example customer */
      target_type: string;
      target_id: string;
      request_id: string;
      details: {
        [key: string]: unknown;
      };
    };
    AuditEventPage: {
      items: components["schemas"]["AuditEvent"][];
      next_page_token?: string;
    };
    KratosHookPayload: {
      /** Format: uuid */
      identity_id: string;
      schema_id: string;
      /** @enum {string} */
      flow_type: "api" | "browser";
    };
  };
  responses: {
    /** @description Error (RFC 9457) */
    Problem: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/problem+json": components["schemas"]["Problem"];
      };
    };
  };
  parameters: {
    IdentityId: string;
    PageSize: number;
    PageToken: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  updateMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMeRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Me"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  getMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  putMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PersonalInfo"];
      };
    };
    responses: {
      /** @description Stored */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  eraseMyPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Erased */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  getAdminMe: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminMe"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  listCustomers: {
    parameters: {
      query?: {
        email?: string;
        state?: components["schemas"]["IdentityState"];
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  lookupCustomers: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerLookupRequest"];
      };
    };
    responses: {
      /** @description Matches (possibly empty) */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerLookupResult"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getCustomerPersonalInfoMasked: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaskedPersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  revealCustomerPersonalInfo: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RevealRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonalInfo"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
      429: components["responses"]["Problem"];
      503: components["responses"]["Problem"];
    };
  };
  getCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Customer"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  disableCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReasonRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerState"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  enableCustomer: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["ReasonRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CustomerState"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  revokeCustomerSessions: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Revoked */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
    };
  };
  listAdmins: {
    parameters: {
      query?: {
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  inviteAdmin: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InviteAdminRequest"];
      };
    };
    responses: {
      /** @description Invited */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["InvitedAdmin"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  changeAdminRole: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: components["parameters"]["IdentityId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ChangeRoleRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Admin"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
      404: components["responses"]["Problem"];
      409: components["responses"]["Problem"];
      422: components["responses"]["Problem"];
    };
  };
  listAuditEvents: {
    parameters: {
      query?: {
        target_type?: string;
        target_id?: string;
        actor_id?: string;
        page_size?: components["parameters"]["PageSize"];
        page_token?: components["parameters"]["PageToken"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuditEventPage"];
        };
      };
      401: components["responses"]["Problem"];
      403: components["responses"]["Problem"];
    };
  };
  kratosAfterRegistration: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosHookPayload"];
      };
    };
    responses: {
      /** @description Processed (idempotent) */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  kratosAfterLogin: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["KratosHookPayload"];
      };
    };
    responses: {
      /** @description Allowed */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad key */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Login interrupted (Kratos webhook message format) */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
