// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_event (actor_identity_id, action, target_type, target_id, request_id, client_ip, details)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, occurred_at
`

type InsertAuditEventParams struct {
	ActorIdentityID uuid.UUID
	Action          string
	TargetType      string
	TargetID        string
	RequestID       string
	ClientIp        *netip.Addr
	Details         []byte
}

type InsertAuditEventRow struct {
	ID         int64
	OccurredAt time.Time
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (InsertAuditEventRow, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ActorIdentityID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.RequestID,
		arg.ClientIp,
		arg.Details,
	)
	var i InsertAuditEventRow
	err := row.Scan(&i.ID, &i.OccurredAt)
	return i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor_identity_id, action, target_type, target_id, request_id, details
FROM audit_event
WHERE ($1::text IS NULL OR target_type = $1::text)
  AND ($2::text IS NULL OR target_id = $2::text)
  AND ($3::uuid IS NULL OR actor_identity_id = $3::uuid)
  -- Optional action allowlist (machine audit feed): exact names or LIKE
  -- prefixes (escaped by the caller). Both NULL = no restriction.
  AND (($4::text[] IS NULL AND $5::text[] IS NULL)
       OR action = ANY(COALESCE($4::text[], '{}'::text[]))
       OR action LIKE ANY(COALESCE($5::text[], '{}'::text[])))
  AND ($6::timestamptz IS NULL
       OR (occurred_at, id) < ($6::timestamptz, $7::bigint))
ORDER BY occurred_at DESC, id DESC
LIMIT $8
`

type ListAuditEventsParams struct {
	TargetType      *string
	TargetID        *string
	ActorID         uuid.NullUUID
	Actions         []string
	ActionPatterns  []string
	AfterOccurredAt *time.Time
	AfterID         *int64
	PageLimit       int32
}

type ListAuditEventsRow struct {
	ID              int64
	OccurredAt      time.Time
	ActorIdentityID uuid.UUID
	Action          string
	TargetType      string
	TargetID        string
	RequestID       string
	Details         []byte
}

// Keyset pagination on (occurred_at, id), newest first.
func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TargetType,
		arg.TargetID,
		arg.ActorID,
		arg.Actions,
		arg.ActionPatterns,
		arg.AfterOccurredAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorIdentityID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.RequestID,
			&i.Details,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
