// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :execrows
UPDATE idempotency_key
SET response_code = $1, response_body = $2
WHERE actor_identity_id = $3 AND key = $4 AND response_code = 0
`

type CompleteIdempotencyKeyParams struct {
	ResponseCode    int32
	ResponseBody    []byte
	ActorIdentityID uuid.UUID
	Key             string
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.ResponseCode,
		arg.ResponseBody,
		arg.ActorIdentityID,
		arg.Key,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredIdempotencyKeyFor = `-- name: DeleteExpiredIdempotencyKeyFor :exec
DELETE FROM idempotency_key
WHERE actor_identity_id = $1 AND key = $2 AND created_at <= $3
`

type DeleteExpiredIdempotencyKeyForParams struct {
	ActorIdentityID uuid.UUID
	Key             string
	NotBefore       time.Time
}

func (q *Queries) DeleteExpiredIdempotencyKeyFor(ctx context.Context, arg DeleteExpiredIdempotencyKeyForParams) error {
	_, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeyFor, arg.ActorIdentityID, arg.Key, arg.NotBefore)
	return err
}

const deleteExpiredIdempotencyKeys = `-- name: DeleteExpiredIdempotencyKeys :execrows
DELETE FROM idempotency_key WHERE created_at <= $1
`

func (q *Queries) DeleteExpiredIdempotencyKeys(ctx context.Context, notBefore time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredIdempotencyKeys, notBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteIdempotencyKey = `-- name: DeleteIdempotencyKey :exec
DELETE FROM idempotency_key WHERE actor_identity_id = $1 AND key = $2
`

type DeleteIdempotencyKeyParams struct {
	ActorIdentityID uuid.UUID
	Key             string
}

func (q *Queries) DeleteIdempotencyKey(ctx context.Context, arg DeleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, deleteIdempotencyKey, arg.ActorIdentityID, arg.Key)
	return err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT request_hash, response_code, response_body, created_at
FROM idempotency_key
WHERE actor_identity_id = $1 AND key = $2
`

type GetIdempotencyKeyParams struct {
	ActorIdentityID uuid.UUID
	Key             string
}

type GetIdempotencyKeyRow struct {
	RequestHash  []byte
	ResponseCode int32
	ResponseBody []byte
	CreatedAt    time.Time
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.ActorIdentityID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.CreatedAt,
	)
	return i, err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :execrows
INSERT INTO idempotency_key (key, actor_identity_id, request_hash, response_code, response_body)
VALUES ($1, $2, $3, 0, '{}'::jsonb)
ON CONFLICT (actor_identity_id, key) DO NOTHING
`

type ReserveIdempotencyKeyParams struct {
	Key             string
	ActorIdentityID uuid.UUID
	RequestHash     []byte
}

// A pending reservation has response_code 0.
func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveIdempotencyKey, arg.Key, arg.ActorIdentityID, arg.RequestHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
