// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lock.sql

package sqlcgen

import (
	"context"
)

const advisoryXactLock = `-- name: AdvisoryXactLock :exec
SELECT pg_advisory_xact_lock($1::bigint)
`

func (q *Queries) AdvisoryXactLock(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, advisoryXactLock, lockKey)
	return err
}
