// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: login.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bindLoginIdentifier = `-- name: BindLoginIdentifier :execrows
UPDATE login_identifier
SET identity_id = $1, bound_at = COALESCE(CASE WHEN identity_id = $1 THEN bound_at END, now())
WHERE pseudonym = $2
  AND (identity_id IS NULL OR identity_id = $1 OR identity_id = $3)
`

type BindLoginIdentifierParams struct {
	IdentityID    uuid.NullUUID
	Pseudonym     []byte
	StaleIdentity uuid.NullUUID
}

// Binds when unbound or already bound to the same identity; with
// stale_identity it also replaces exactly that binding (the caller verified
// that identity is gone), never a binding made meanwhile.
func (q *Queries) BindLoginIdentifier(ctx context.Context, arg BindLoginIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindLoginIdentifier, arg.IdentityID, arg.Pseudonym, arg.StaleIdentity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCourierDeliveriesTo = `-- name: CountCourierDeliveriesTo :one
SELECT count(*) FROM courier_dispatch
WHERE recipient_key = $1 AND channel IS NOT NULL AND updated_at >= $2
`

type CountCourierDeliveriesToParams struct {
	RecipientKey []byte
	Since        time.Time
}

func (q *Queries) CountCourierDeliveriesTo(ctx context.Context, arg CountCourierDeliveriesToParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCourierDeliveriesTo, arg.RecipientKey, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSMSDeliveries = `-- name: CountSMSDeliveries :one
SELECT count(*) FROM courier_dispatch
WHERE channel = 'sms' AND updated_at >= $1 AND ($2::text = '' OR country = $2::text)
`

type CountSMSDeliveriesParams struct {
	Since   time.Time
	Country string
}

// country ” = every country.
func (q *Queries) CountSMSDeliveries(ctx context.Context, arg CountSMSDeliveriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSMSDeliveries, arg.Since, arg.Country)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnboundLoginIdentifiers = `-- name: CountUnboundLoginIdentifiers :one
SELECT count(*) FROM login_identifier WHERE identity_id IS NULL
`

func (q *Queries) CountUnboundLoginIdentifiers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnboundLoginIdentifiers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteErasedLoginIdentifiers = `-- name: DeleteErasedLoginIdentifiers :execrows
DELETE FROM login_identifier l
USING (
  SELECT DISTINCT target_id
  FROM audit_event
  WHERE action = 'customer.login.erased' AND target_type = 'customer'
) e
WHERE l.identity_id::text = e.target_id
`

// Erasure ledger: logins of identities with a customer.login.erased event
// (re-applied after a restore).
func (q *Queries) DeleteErasedLoginIdentifiers(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteErasedLoginIdentifiers)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginIdentifier = `-- name: DeleteLoginIdentifier :execrows
DELETE FROM login_identifier
WHERE pseudonym = $1 AND (NOT $2::boolean OR identity_id IS NULL)
`

type DeleteLoginIdentifierParams struct {
	Pseudonym     []byte
	OnlyIfUnbound bool
}

func (q *Queries) DeleteLoginIdentifier(ctx context.Context, arg DeleteLoginIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLoginIdentifier, arg.Pseudonym, arg.OnlyIfUnbound)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLoginIdentifierForIdentity = `-- name: DeleteLoginIdentifierForIdentity :execrows
DELETE FROM login_identifier WHERE identity_id = $1
`

func (q *Queries) DeleteLoginIdentifierForIdentity(ctx context.Context, identityID uuid.NullUUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLoginIdentifierForIdentity, identityID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteStaleUnboundLoginIdentifier = `-- name: DeleteStaleUnboundLoginIdentifier :execrows
DELETE FROM login_identifier
WHERE pseudonym = $1 AND identity_id IS NULL AND last_validated_at < $2
`

type DeleteStaleUnboundLoginIdentifierParams struct {
	Pseudonym []byte
	Before    time.Time
}

// Purge (A10): deletes only while still unbound and not validated since
// @before, so a registration that validated the row meanwhile keeps it.
func (q *Queries) DeleteStaleUnboundLoginIdentifier(ctx context.Context, arg DeleteStaleUnboundLoginIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleUnboundLoginIdentifier, arg.Pseudonym, arg.Before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getLoginIdentifier = `-- name: GetLoginIdentifier :one
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE pseudonym = $1
`

func (q *Queries) GetLoginIdentifier(ctx context.Context, pseudonym []byte) (LoginIdentifier, error) {
	row := q.db.QueryRow(ctx, getLoginIdentifier, pseudonym)
	var i LoginIdentifier
	err := row.Scan(
		&i.Pseudonym,
		&i.Kind,
		&i.ValueCt,
		&i.KekVersion,
		&i.IdentityID,
		&i.BoundAt,
		&i.LegacyVerified,
		&i.CreatedAt,
		&i.LastValidatedAt,
	)
	return i, err
}

const getLoginIdentifierByIdentity = `-- name: GetLoginIdentifierByIdentity :one
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE identity_id = $1
`

func (q *Queries) GetLoginIdentifierByIdentity(ctx context.Context, identityID uuid.NullUUID) (LoginIdentifier, error) {
	row := q.db.QueryRow(ctx, getLoginIdentifierByIdentity, identityID)
	var i LoginIdentifier
	err := row.Scan(
		&i.Pseudonym,
		&i.Kind,
		&i.ValueCt,
		&i.KekVersion,
		&i.IdentityID,
		&i.BoundAt,
		&i.LegacyVerified,
		&i.CreatedAt,
		&i.LastValidatedAt,
	)
	return i, err
}

const getLoginIdentifiers = `-- name: GetLoginIdentifiers :many
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE pseudonym = ANY($1::bytea[])
`

func (q *Queries) GetLoginIdentifiers(ctx context.Context, pseudonyms [][]byte) ([]LoginIdentifier, error) {
	rows, err := q.db.Query(ctx, getLoginIdentifiers, pseudonyms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginIdentifier{}
	for rows.Next() {
		var i LoginIdentifier
		if err := rows.Scan(
			&i.Pseudonym,
			&i.Kind,
			&i.ValueCt,
			&i.KekVersion,
			&i.IdentityID,
			&i.BoundAt,
			&i.LegacyVerified,
			&i.CreatedAt,
			&i.LastValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLoginIdentifier = `-- name: InsertLoginIdentifier :execrows
INSERT INTO login_identifier (pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified)
VALUES ($1, $2, $3, $4, $5,
        CASE WHEN $5::uuid IS NULL THEN NULL ELSE now() END, $6)
ON CONFLICT (pseudonym) DO NOTHING
`

type InsertLoginIdentifierParams struct {
	Pseudonym      []byte
	Kind           string
	ValueCt        string
	KekVersion     int32
	IdentityID     uuid.NullUUID
	LegacyVerified bool
}

// Registration resolve (PLI-FR-02): idempotent insert.
func (q *Queries) InsertLoginIdentifier(ctx context.Context, arg InsertLoginIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertLoginIdentifier,
		arg.Pseudonym,
		arg.Kind,
		arg.ValueCt,
		arg.KekVersion,
		arg.IdentityID,
		arg.LegacyVerified,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listAllLoginIdentifiers = `-- name: ListAllLoginIdentifiers :many
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE pseudonym > $1
ORDER BY pseudonym
LIMIT $2
`

type ListAllLoginIdentifiersParams struct {
	After     []byte
	PageLimit int32
}

func (q *Queries) ListAllLoginIdentifiers(ctx context.Context, arg ListAllLoginIdentifiersParams) ([]LoginIdentifier, error) {
	rows, err := q.db.Query(ctx, listAllLoginIdentifiers, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginIdentifier{}
	for rows.Next() {
		var i LoginIdentifier
		if err := rows.Scan(
			&i.Pseudonym,
			&i.Kind,
			&i.ValueCt,
			&i.KekVersion,
			&i.IdentityID,
			&i.BoundAt,
			&i.LegacyVerified,
			&i.CreatedAt,
			&i.LastValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoundLoginIdentifiers = `-- name: ListBoundLoginIdentifiers :many
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE identity_id IS NOT NULL AND pseudonym > $1
ORDER BY pseudonym
LIMIT $2
`

type ListBoundLoginIdentifiersParams struct {
	After     []byte
	PageLimit int32
}

func (q *Queries) ListBoundLoginIdentifiers(ctx context.Context, arg ListBoundLoginIdentifiersParams) ([]LoginIdentifier, error) {
	rows, err := q.db.Query(ctx, listBoundLoginIdentifiers, arg.After, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginIdentifier{}
	for rows.Next() {
		var i LoginIdentifier
		if err := rows.Scan(
			&i.Pseudonym,
			&i.Kind,
			&i.ValueCt,
			&i.KekVersion,
			&i.IdentityID,
			&i.BoundAt,
			&i.LegacyVerified,
			&i.CreatedAt,
			&i.LastValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleUnboundLoginIdentifiers = `-- name: ListStaleUnboundLoginIdentifiers :many
SELECT pseudonym, kind, value_ct, kek_version, identity_id, bound_at, legacy_verified, created_at, last_validated_at
FROM login_identifier
WHERE identity_id IS NULL AND last_validated_at < $1
ORDER BY last_validated_at
LIMIT $2
`

type ListStaleUnboundLoginIdentifiersParams struct {
	Before    time.Time
	PageLimit int32
}

// Purge (A10): unbound rows not validated since @before.
func (q *Queries) ListStaleUnboundLoginIdentifiers(ctx context.Context, arg ListStaleUnboundLoginIdentifiersParams) ([]LoginIdentifier, error) {
	rows, err := q.db.Query(ctx, listStaleUnboundLoginIdentifiers, arg.Before, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LoginIdentifier{}
	for rows.Next() {
		var i LoginIdentifier
		if err := rows.Scan(
			&i.Pseudonym,
			&i.Kind,
			&i.ValueCt,
			&i.KekVersion,
			&i.IdentityID,
			&i.BoundAt,
			&i.LegacyVerified,
			&i.CreatedAt,
			&i.LastValidatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markCourierDispatchSent = `-- name: MarkCourierDispatchSent :execrows
UPDATE courier_dispatch
SET state = 'sent', channel = $1, country = $2,
    recipient_key = $3, updated_at = now()
WHERE dedupe_key = $4
`

type MarkCourierDispatchSentParams struct {
	Channel      *string
	Country      *string
	RecipientKey []byte
	DedupeKey    []byte
}

// Delivered messages record channel/country/recipient (quota counting);
// permanently dropped ones are marked sent with NULLs (not counted).
func (q *Queries) MarkCourierDispatchSent(ctx context.Context, arg MarkCourierDispatchSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markCourierDispatchSent,
		arg.Channel,
		arg.Country,
		arg.RecipientKey,
		arg.DedupeKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeCourierDispatch = `-- name: PurgeCourierDispatch :execrows
DELETE FROM courier_dispatch WHERE created_at < $1
`

func (q *Queries) PurgeCourierDispatch(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeCourierDispatch, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseCourierDispatch = `-- name: ReleaseCourierDispatch :execrows
DELETE FROM courier_dispatch WHERE dedupe_key = $1 AND state = 'pending'
`

func (q *Queries) ReleaseCourierDispatch(ctx context.Context, dedupeKey []byte) (int64, error) {
	result, err := q.db.Exec(ctx, releaseCourierDispatch, dedupeKey)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveCourierDispatch = `-- name: ReserveCourierDispatch :execrows
INSERT INTO courier_dispatch (dedupe_key, state) VALUES ($1, 'pending')
ON CONFLICT (dedupe_key) DO UPDATE SET updated_at = now()
WHERE courier_dispatch.state = 'pending' AND courier_dispatch.updated_at < $2
`

type ReserveCourierDispatchParams struct {
	DedupeKey   []byte
	StaleBefore time.Time
}

// A9: claim a key; a stale pending reservation (crashed sender) is retaken.
func (q *Queries) ReserveCourierDispatch(ctx context.Context, arg ReserveCourierDispatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, reserveCourierDispatch, arg.DedupeKey, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setLoginLegacyVerified = `-- name: SetLoginLegacyVerified :execrows
UPDATE login_identifier SET legacy_verified = $1 WHERE pseudonym = $2
`

type SetLoginLegacyVerifiedParams struct {
	LegacyVerified bool
	Pseudonym      []byte
}

func (q *Queries) SetLoginLegacyVerified(ctx context.Context, arg SetLoginLegacyVerifiedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLoginLegacyVerified, arg.LegacyVerified, arg.Pseudonym)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchLoginIdentifier = `-- name: TouchLoginIdentifier :execrows
UPDATE login_identifier SET last_validated_at = now() WHERE pseudonym = $1
`

func (q *Queries) TouchLoginIdentifier(ctx context.Context, pseudonym []byte) (int64, error) {
	result, err := q.db.Exec(ctx, touchLoginIdentifier, pseudonym)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLoginCiphertext = `-- name: UpdateLoginCiphertext :execrows
UPDATE login_identifier SET value_ct = $1, kek_version = $2
WHERE pseudonym = $3 AND value_ct = $4
`

type UpdateLoginCiphertextParams struct {
	NewValueCt string
	KekVersion int32
	Pseudonym  []byte
	OldValueCt string
}

// Re-wrap: optimistic, only if nobody changed (or deleted) the row meanwhile.
func (q *Queries) UpdateLoginCiphertext(ctx context.Context, arg UpdateLoginCiphertextParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLoginCiphertext,
		arg.NewValueCt,
		arg.KekVersion,
		arg.Pseudonym,
		arg.OldValueCt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
