// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type AuditEvent struct {
	ID              int64
	OccurredAt      time.Time
	ActorIdentityID uuid.UUID
	Action          string
	TargetType      string
	TargetID        string
	RequestID       string
	ClientIp        *netip.Addr
	Details         []byte
}

type CourierDispatch struct {
	DedupeKey    []byte
	State        string
	Channel      *string
	Country      *string
	RecipientKey []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CustomerPii struct {
	IdentityID     uuid.UUID
	KeyID          uuid.UUID
	PhoneCt        []byte
	PhoneBidx      []byte
	BidxKeyVersion *int32
	DobCt          []byte
	AddressCt      []byte
	NationalIDCt   []byte
	UpdatedAt      time.Time
	NameCt         []byte
}

type IdempotencyKey struct {
	Key             string
	ActorIdentityID uuid.UUID
	RequestHash     []byte
	ResponseCode    int32
	ResponseBody    []byte
	CreatedAt       time.Time
}

type LoginIdentifier struct {
	Pseudonym       []byte
	Kind            string
	ValueCt         string
	KekVersion      int32
	IdentityID      uuid.NullUUID
	BoundAt         *time.Time
	LegacyVerified  bool
	CreatedAt       time.Time
	LastValidatedAt time.Time
	LookupKey       []byte
}

type Profile struct {
	IdentityID  uuid.UUID
	Kind        string
	DisplayName *string
	AvatarUrl   *string
	Locale      string
	Preferences []byte
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   *time.Time
}

type SubjectKey struct {
	KeyID       uuid.UUID
	IdentityID  uuid.UUID
	WrappedDek  string
	KekName     string
	KekVersion  int32
	CreatedAt   time.Time
	RewrappedAt *time.Time
}
