// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pii.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteErasedSubjectKeys = `-- name: DeleteErasedSubjectKeys :execrows
DELETE FROM subject_key k
USING (
  SELECT target_id, max(occurred_at) AS erased_at
  FROM audit_event
  WHERE action = 'customer.pii.erased' AND target_type = 'customer'
  GROUP BY target_id
) e
WHERE k.identity_id::text = e.target_id AND k.created_at <= e.erased_at
`

// Erasure ledger (§9 B1): delete keys created at or before the subject's
// latest customer.pii.erased audit event (run after any restore).
func (q *Queries) DeleteErasedSubjectKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteErasedSubjectKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSubjectKey = `-- name: DeleteSubjectKey :many
DELETE FROM subject_key WHERE identity_id = $1
RETURNING key_id
`

// Cascades to customer_pii (crypto-shredding).
func (q *Queries) DeleteSubjectKey(ctx context.Context, identityID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteSubjectKey, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var key_id uuid.UUID
		if err := rows.Scan(&key_id); err != nil {
			return nil, err
		}
		items = append(items, key_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findCustomerPIIByPhoneBidx = `-- name: FindCustomerPIIByPhoneBidx :many
SELECT identity_id, key_id, phone_ct, phone_bidx, bidx_key_version, dob_ct, address_ct, national_id_ct, updated_at
FROM customer_pii
WHERE phone_bidx = $1 AND bidx_key_version = $2
ORDER BY identity_id
LIMIT $3
`

type FindCustomerPIIByPhoneBidxParams struct {
	PhoneBidx      []byte
	BidxKeyVersion *int32
	PageLimit      int32
}

func (q *Queries) FindCustomerPIIByPhoneBidx(ctx context.Context, arg FindCustomerPIIByPhoneBidxParams) ([]CustomerPii, error) {
	rows, err := q.db.Query(ctx, findCustomerPIIByPhoneBidx, arg.PhoneBidx, arg.BidxKeyVersion, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomerPii{}
	for rows.Next() {
		var i CustomerPii
		if err := rows.Scan(
			&i.IdentityID,
			&i.KeyID,
			&i.PhoneCt,
			&i.PhoneBidx,
			&i.BidxKeyVersion,
			&i.DobCt,
			&i.AddressCt,
			&i.NationalIDCt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCustomerPII = `-- name: GetCustomerPII :one
SELECT identity_id, key_id, phone_ct, phone_bidx, bidx_key_version, dob_ct, address_ct, national_id_ct, updated_at
FROM customer_pii
WHERE identity_id = $1
`

func (q *Queries) GetCustomerPII(ctx context.Context, identityID uuid.UUID) (CustomerPii, error) {
	row := q.db.QueryRow(ctx, getCustomerPII, identityID)
	var i CustomerPii
	err := row.Scan(
		&i.IdentityID,
		&i.KeyID,
		&i.PhoneCt,
		&i.PhoneBidx,
		&i.BidxKeyVersion,
		&i.DobCt,
		&i.AddressCt,
		&i.NationalIDCt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSubjectKey = `-- name: GetSubjectKey :one
SELECT key_id, identity_id, wrapped_dek, kek_name, kek_version, created_at, rewrapped_at
FROM subject_key
WHERE identity_id = $1
`

func (q *Queries) GetSubjectKey(ctx context.Context, identityID uuid.UUID) (SubjectKey, error) {
	row := q.db.QueryRow(ctx, getSubjectKey, identityID)
	var i SubjectKey
	err := row.Scan(
		&i.KeyID,
		&i.IdentityID,
		&i.WrappedDek,
		&i.KekName,
		&i.KekVersion,
		&i.CreatedAt,
		&i.RewrappedAt,
	)
	return i, err
}

const insertSubjectKey = `-- name: InsertSubjectKey :one
INSERT INTO subject_key (key_id, identity_id, wrapped_dek, kek_name, kek_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (identity_id) DO NOTHING
RETURNING key_id, identity_id, wrapped_dek, kek_name, kek_version, created_at, rewrapped_at
`

type InsertSubjectKeyParams struct {
	KeyID      uuid.UUID
	IdentityID uuid.UUID
	WrappedDek string
	KekName    string
	KekVersion int32
}

// No row is returned when the subject already has a key (the caller re-reads).
func (q *Queries) InsertSubjectKey(ctx context.Context, arg InsertSubjectKeyParams) (SubjectKey, error) {
	row := q.db.QueryRow(ctx, insertSubjectKey,
		arg.KeyID,
		arg.IdentityID,
		arg.WrappedDek,
		arg.KekName,
		arg.KekVersion,
	)
	var i SubjectKey
	err := row.Scan(
		&i.KeyID,
		&i.IdentityID,
		&i.WrappedDek,
		&i.KekName,
		&i.KekVersion,
		&i.CreatedAt,
		&i.RewrappedAt,
	)
	return i, err
}

const listSubjectKeysForRewrap = `-- name: ListSubjectKeysForRewrap :many
SELECT key_id, identity_id, wrapped_dek, kek_name, kek_version, created_at, rewrapped_at
FROM subject_key
WHERE key_id > $1
ORDER BY key_id
LIMIT $2
`

type ListSubjectKeysForRewrapParams struct {
	AfterKeyID uuid.UUID
	PageLimit  int32
}

func (q *Queries) ListSubjectKeysForRewrap(ctx context.Context, arg ListSubjectKeysForRewrapParams) ([]SubjectKey, error) {
	rows, err := q.db.Query(ctx, listSubjectKeysForRewrap, arg.AfterKeyID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubjectKey{}
	for rows.Next() {
		var i SubjectKey
		if err := rows.Scan(
			&i.KeyID,
			&i.IdentityID,
			&i.WrappedDek,
			&i.KekName,
			&i.KekVersion,
			&i.CreatedAt,
			&i.RewrappedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWrappedDEK = `-- name: UpdateWrappedDEK :execrows
UPDATE subject_key
SET wrapped_dek = $1, kek_name = $2, kek_version = $3, rewrapped_at = now()
WHERE key_id = $4 AND wrapped_dek = $5
`

type UpdateWrappedDEKParams struct {
	NewWrappedDek string
	KekName       string
	KekVersion    int32
	KeyID         uuid.UUID
	OldWrappedDek string
}

// Optimistic: only if nobody changed (or erased) the key meanwhile.
func (q *Queries) UpdateWrappedDEK(ctx context.Context, arg UpdateWrappedDEKParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateWrappedDEK,
		arg.NewWrappedDek,
		arg.KekName,
		arg.KekVersion,
		arg.KeyID,
		arg.OldWrappedDek,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCustomerPII = `-- name: UpsertCustomerPII :one
INSERT INTO customer_pii (identity_id, key_id, phone_ct, phone_bidx, bidx_key_version, dob_ct, address_ct, national_id_ct, updated_at)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, now())
ON CONFLICT (identity_id) DO UPDATE
SET key_id           = EXCLUDED.key_id,
    phone_ct         = EXCLUDED.phone_ct,
    phone_bidx       = EXCLUDED.phone_bidx,
    bidx_key_version = EXCLUDED.bidx_key_version,
    dob_ct           = EXCLUDED.dob_ct,
    address_ct       = EXCLUDED.address_ct,
    national_id_ct   = EXCLUDED.national_id_ct,
    updated_at       = now()
RETURNING updated_at
`

type UpsertCustomerPIIParams struct {
	IdentityID     uuid.UUID
	KeyID          uuid.UUID
	PhoneCt        []byte
	PhoneBidx      []byte
	BidxKeyVersion *int32
	DobCt          []byte
	AddressCt      []byte
	NationalIDCt   []byte
}

func (q *Queries) UpsertCustomerPII(ctx context.Context, arg UpsertCustomerPIIParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, upsertCustomerPII,
		arg.IdentityID,
		arg.KeyID,
		arg.PhoneCt,
		arg.PhoneBidx,
		arg.BidxKeyVersion,
		arg.DobCt,
		arg.AddressCt,
		arg.NationalIDCt,
	)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
