// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getProfile = `-- name: GetProfile :one
SELECT identity_id, kind, display_name, avatar_url, locale, created_at, updated_at
FROM profile
WHERE identity_id = $1 AND deleted_at IS NULL
`

type GetProfileRow struct {
	IdentityID  uuid.UUID
	Kind        string
	DisplayName *string
	AvatarUrl   *string
	Locale      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProfile(ctx context.Context, identityID uuid.UUID) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, identityID)
	var i GetProfileRow
	err := row.Scan(
		&i.IdentityID,
		&i.Kind,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfilesByIDs = `-- name: GetProfilesByIDs :many
SELECT identity_id, kind, display_name, avatar_url, locale, created_at, updated_at
FROM profile
WHERE identity_id = ANY($1::uuid[]) AND deleted_at IS NULL
`

type GetProfilesByIDsRow struct {
	IdentityID  uuid.UUID
	Kind        string
	DisplayName *string
	AvatarUrl   *string
	Locale      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) GetProfilesByIDs(ctx context.Context, ids []uuid.UUID) ([]GetProfilesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getProfilesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProfilesByIDsRow{}
	for rows.Next() {
		var i GetProfilesByIDsRow
		if err := rows.Scan(
			&i.IdentityID,
			&i.Kind,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Locale,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProfileIfAbsent = `-- name: InsertProfileIfAbsent :exec
INSERT INTO profile (identity_id, kind)
VALUES ($1, $2)
ON CONFLICT (identity_id) DO NOTHING
`

type InsertProfileIfAbsentParams struct {
	IdentityID uuid.UUID
	Kind       string
}

func (q *Queries) InsertProfileIfAbsent(ctx context.Context, arg InsertProfileIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertProfileIfAbsent, arg.IdentityID, arg.Kind)
	return err
}

const updateProfile = `-- name: UpdateProfile :one
UPDATE profile
SET display_name = $1,
    avatar_url   = $2,
    locale       = $3,
    updated_at   = now()
WHERE identity_id = $4 AND deleted_at IS NULL
RETURNING identity_id, kind, display_name, avatar_url, locale, created_at, updated_at
`

type UpdateProfileParams struct {
	DisplayName *string
	AvatarUrl   *string
	Locale      string
	IdentityID  uuid.UUID
}

type UpdateProfileRow struct {
	IdentityID  uuid.UUID
	Kind        string
	DisplayName *string
	AvatarUrl   *string
	Locale      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) UpdateProfile(ctx context.Context, arg UpdateProfileParams) (UpdateProfileRow, error) {
	row := q.db.QueryRow(ctx, updateProfile,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Locale,
		arg.IdentityID,
	)
	var i UpdateProfileRow
	err := row.Scan(
		&i.IdentityID,
		&i.Kind,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
